In [6]:
import pandas as pd
import numpy as np
import math
from tqdm import tqdm

In [7]:
# get size of vector
def mag(x):
    return math.sqrt(sum(i**2 for i in x))

In [14]:
p_m = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data/강남구_restuarant_normalized_item_matrix.csv')
u_m = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data/강남구_restuarant_normalized_user_matrix.csv')
group_count = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data/강남구_restuarant_group_count.csv')

# res_matrix.rename(columns ={'Unnamed: 0':'p_id' }, inplace =True)
p_m.set_index('p_id', inplace =True)
# user_matrix.rename(columns ={'Unnamed: 0':'u_id' }, inplace =True)
u_m.set_index('u_id', inplace =True)
# group_count.rename(columns ={'Unnamed: 0':'group' }, inplace =True)
# group_count.set_index('group', inplace =True)
# res_matrix.set_index('p_id', drop=True, inplace=True)
# user_matrix.set_index('u_id', drop=True, inplace=True)
# group_count.set_index('group', drop=True, inplace=True)

In [15]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [16]:
group_count

         group  count
0     group_73   1291
1      group_0      1
2      group_1    382
3      group_2     45
4      group_3     37
..         ...    ...
115  group_115    103
116  group_116     93
117  group_117     29
118  group_118      1
119  group_119      9

[120 rows x 2 columns]

In [17]:
group_count.set_index('group', inplace =True)

In [18]:
group_count

           count
group
group_73    1291
group_0        1
group_1      382
group_2       45
group_3       37
...          ...
group_115    103
group_116     93
group_117     29
group_118      1
group_119      9

[120 rows x 1 columns]

In [19]:
p_m

,0,1,2,3,4,5,6,7,8,9,...,110,111,112,113,114,115,116,117,118,119
p_id,,,,,,,,,,,,,,,,,,,,,
0,0.001151,0.0,0.010374,0.000000,0.013388,0.013760,0.000000,0.000000,0.024522,0.056290,...,0.016697,0.006518,0.007051,0.000000,0.000000,0.000000,0.000000,0.017081,0.000000,0.0000
1,0.002574,0.0,0.008699,0.022153,0.008981,0.000000,0.006153,0.000000,0.013160,0.113280,...,0.000000,0.004372,0.004730,0.005729,0.008744,0.000000,0.003573,0.045833,0.000000,0.0000
2,0.002991,0.0,0.004354,0.007920,0.000000,0.008250,0.004400,0.006854,0.001764,0.050851,...,0.004005,0.002345,0.000423,0.003072,0.018758,0.002307,0.001277,0.088078,0.000000,0.0198
3,0.002100,0.0,0.003205,0.000000,0.000000,0.012146,0.001619,0.000000,0.001732,0.013912,...,0.006878,0.002301,0.001867,0.004523,0.009205,0.002547,0.001881,0.045232,0.087449,0.0000
4,0.003296,0.0,0.005221,0.002955,0.007187,0.011080,0.004925,0.000000,0.005266,0.025183,...,0.016434,0.005249,0.004732,0.002293,0.003499,0.000000,0.005719,0.050435,0.000000,0.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
768,0.000662,0.0,0.006717,0.000000,0.000000,0.000000,0.000000,0.000000,0.008468,0.019438,...,0.000000,0.000000,0.030437,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000
769,0.003246,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.013830,0.021163,...,0.000000,0.000000,0.000000,0.000000,0.036757,0.000000,0.000000,0.000000,0.000000,0.0000
770,0.013393,0.0,0.000000,0.192109,0.000000,0.000000,0.000000,0.000000,0.000000,0.130983,...,0.000000,0.000000,0.030765,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000
771,0.006584,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.064397,...,0.000000,0.000000,0.060501,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000
772,0.013287,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.030522,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000

In [20]:
u_m

,0,1,2,3,4,5,6,7,8,9,...,110,111,112,113,114,115,116,117,118,119
u_id,,,,,,,,,,,,,,,,,,,,,
559,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,...,0.000000,0.0,0.00000,0.0,0.0,0.000000,0.0,0.00000,0.0,0.0
3735,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,...,0.000000,0.0,0.00000,0.0,0.0,0.000000,0.0,0.00000,0.0,0.0
1961,0.004821,0.0,0.0,0.0,0.252345,0.000000,0.000000,0.0,0.061629,0.070733,...,0.000000,0.0,0.00000,0.0,0.0,0.000000,0.0,0.00000,0.0,0.0
4100,0.000000,0.0,0.0,0.0,0.000000,0.116959,0.000000,0.0,0.041689,0.095694,...,0.000000,0.0,0.00000,0.0,0.0,0.000000,0.0,0.00000,0.0,0.0
3990,0.005080,0.0,0.0,0.0,0.000000,0.000000,0.020243,0.0,0.027057,0.008281,...,0.012282,0.0,0.00778,0.0,0.0,0.010613,0.0,0.05654,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1899,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,...,0.000000,0.0,0.00000,0.0,0.0,0.000000,0.0,0.00000,0.0,0.0
3576,0.018337,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.358685,...,0.000000,0.0,0.00000,0.0,0.0,0.000000,0.0,0.00000,0.0,0.0
494,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.222418,...,0.000000,0.0,0.00000,0.0,0.0,0.000000,0.0,0.00000,0.0,0.0
2949,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,...,0.000000,0.0,0.00000,0.0,0.0,0.000000,0.0,0.00000,0.0,0.0
758,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,...,0.000000,0.0,0.00000,0.0,0.0,0.000000,0.0,0.00000,0.0,0.0

In [21]:
from sklearn.metrics.pairwise import cosine_similarity

def cos_sim_matrix(a,b):
  cos_sim=cosine_similarity(a,b)
  result_df =pd.DataFrame(data=cos_sim, index=[a.index])

  return result_df

In [22]:
#similarity df

In [23]:

cs_u_df = cos_sim_matrix(u_m,u_m)
cs_u_df.head()

,0,1,2,3,4,5,6,7,8,9,...,4171,4172,4173,4174,4175,4176,4177,4178,4179,4180
u_id,,,,,,,,,,,,,,,,,,,,,
559,1.000000,0.0,0.026534,0.284721,0.206460,0.000000,0.000000,0.163193,0.036914,0.006520,...,0.000000,0.000000,0.000000,0.000000,0.022884,0.010880,0.000000,0.000000,0.0,0.0
3735,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
1961,0.026534,0.0,1.000000,0.099173,0.080792,0.116305,0.081190,0.129576,0.033243,0.048551,...,0.020450,0.201906,0.234110,0.132639,0.052115,0.028837,0.101062,0.260394,0.0,0.0
4100,0.284721,0.0,0.099173,1.000000,0.469361,0.078123,0.489327,0.539108,0.032272,0.343970,...,0.018340,0.271246,0.062624,0.000000,0.204629,0.009685,0.135298,0.172905,0.0,0.0
3990,0.206460,0.0,0.080792,0.469361,1.000000,0.119936,0.449631,0.481295,0.073130,0.400814,...,0.140384,0.036645,0.077500,0.000000,0.163839,0.026410,0.018852,0.066803,0.0,0.0

In [24]:
cs_p_df = cos_sim_matrix(p_m,p_m)
cs_p_df.head()

,0,1,2,3,4,5,6,7,8,9,...,763,764,765,766,767,768,769,770,771,772
p_id,,,,,,,,,,,,,,,,,,,,,
0,1.000000,0.749308,0.700428,0.479815,0.259435,0.461126,0.661770,0.429600,0.259785,0.480948,...,0.559776,0.609220,0.474774,0.447305,0.101857,0.631867,0.217630,0.138852,0.590525,0.285739
1,0.749308,1.000000,0.835294,0.466250,0.311366,0.533644,0.703401,0.472172,0.346305,0.604104,...,0.667658,0.775708,0.509072,0.676496,0.123353,0.594841,0.198422,0.271419,0.685484,0.312567
2,0.700428,0.835294,1.000000,0.574372,0.463405,0.555052,0.710930,0.545378,0.501889,0.690889,...,0.626398,0.783987,0.584954,0.495706,0.284888,0.668889,0.209722,0.130705,0.670859,0.373649
3,0.479815,0.466250,0.574372,1.000000,0.442358,0.430127,0.443368,0.517119,0.382739,0.450529,...,0.374343,0.496343,0.451098,0.253617,0.299910,0.356651,0.101105,0.041245,0.360092,0.260587
4,0.259435,0.311366,0.463405,0.442358,1.000000,0.270525,0.202592,0.648652,0.863300,0.256132,...,0.241183,0.289357,0.720281,0.230503,0.868452,0.209167,0.136446,0.061460,0.208831,0.127834

In [25]:
eat_review =pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data/광진구_restaurant_review.csv')
eat_review

,res_name,user_name,review,rating,p_id,u_id
0,모터시티,Mike Kim,Love motor city pizza,5,243,559
1,김북순큰남비집,철준,맛있음,5,88,3735
2,김북순큰남비집,돼후니,"#돼훈맛집 #솔직돼훈맛있고, 든든하게 한식을 먹을 수 있는 곳! -맛 : 3.7점 ...",5,88,1961
3,김북순큰남비집,호리,[신사/김북순 큰남비집] 5/5오 좋다! 소리가 절로 나온 찌개 맛집이오~개인적으로...,5,88,4100
4,김북순큰남비집,하몽이,누구나 아는 맛 그러나 모두가 즐기는 맛 근처에서 뜨끈한 국물에 흰 쌀밥 생각나면 ...,5,88,3990
...,...,...,...,...,...,...
17130,깐부치킨,Crisp.,깐부 처음가서 그런데 구운마늘치킨 먹음.. 맛은 있대 좀 많이 기름진거 같았어요.,3,95,160
17131,깐부치킨,Miriam Park,We ordered the garlic soy chicken. The chicken...,3,95,570
17132,모터시티,호두꽈자,포치즈홀스맨 24900그릴드 치킨 아보카도 샐러드 16900 (발사믹)[공간]생긴 ...,3,243,4095
17133,모터시티,이영훈,디트로이트 스타일 피자 처음먹어보는데 맛있어요 ㅋㅋ 가격은 좀 나가지만 토마토 소스...,5,243,3341
17134,모터시티,Tbone213@u!,Tasted aaamazing as usual and spot on tangy sa...,3,243,758

In [26]:
eat_review['u_id'].value_counts()

812     127
3066    125
2582    123
3520    122
4        94
       ...
3907      1
2674      1
1860      1
3724      1
758       1
Name: u_id, Length: 4181, dtype: int64

In [27]:
eat_review['rating'].value_counts()

5    10576
3     4886
0     1673
Name: rating, dtype: int64

In [28]:
len(eat_review['p_id'].unique())

771

In [29]:
eat_review.drop(['review','res_name','user_name'],axis=1, inplace=True)

In [30]:
eat_review

       rating  p_id  u_id
0           5   243   559
1           5    88  3735
2           5    88  1961
3           5    88  4100
4           5    88  3990
...       ...   ...   ...
17130       3    95   160
17131       3    95   570
17132       3   243  4095
17133       5   243  3341
17134       3   243   758

[17135 rows x 3 columns]

In [31]:
eat_review_mean=eat_review.groupby(['u_id','p_id']).mean()
eat_review_mean

           rating
u_id p_id
0    82       3.0
     114      5.0
     243      3.0
     264      5.0
     306      3.0
...           ...
4180 264      5.0
     382      5.0
     491      3.0
     619      5.0
     659      3.0

[16002 rows x 1 columns]

In [32]:
eat_review_mean.reset_index(level=0, inplace=True)
eat_review_mean.reset_index(level=0, inplace=True)
eat_review_mean

       p_id  u_id  rating
0        82     0     3.0
1       114     0     5.0
2       243     0     3.0
3       264     0     5.0
4       306     0     3.0
...     ...   ...     ...
15997   264  4180     5.0
15998   382  4180     5.0
15999   491  4180     3.0
16000   619  4180     5.0
16001   659  4180     3.0

[16002 rows x 3 columns]

In [33]:
eat_review_mean.shape

(16002, 3)

In [34]:
# eat_review_mean_dropDU=eat_review_mean.drop_duplicates(subset=['u_id','p_id'], keep='first', ignore_index=False)

In [35]:
# eat_review_mean_dropDU.shape

In [36]:
import tensorflow as tf

In [37]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

train_df, test_df = train_test_split(eat_review_mean, test_size=0.2, random_state=123)

In [38]:
train_df.shape

(12801, 3)

In [39]:
test_userids =list(set(test_df['u_id'].values))
len(test_userids)

1654

In [40]:
all_userids =list(set(eat_review_mean['u_id'].values))
len(all_userids)

4181

In [41]:
user_record_df=eat_review[eat_review['u_id']==1567]

In [42]:
user_record_df

      rating  p_id  u_id
725        3   213  1567
4008       0   309  1567
4755       5   659  1567

In [43]:
user_record_df['p_id']

725     213
4008    309
4755    659
Name: p_id, dtype: int64

In [44]:
cs_u_df.loc[user_record_df['p_id']]

,0,1,2,3,4,5,6,7,8,9,...,4171,4172,4173,4174,4175,4176,4177,4178,4179,4180
u_id,,,,,,,,,,,,,,,,,,,,,
213,0.066927,0.0,0.220906,0.427108,0.468874,0.088006,0.427993,0.494450,0.608624,0.315538,...,0.026379,0.336765,0.107697,0.009906,0.186498,0.059579,0.168317,0.229573,0.0,0.0
309,0.000000,0.0,0.111114,0.059549,0.185432,0.000000,0.028008,0.127028,0.168953,0.020912,...,0.022236,0.219540,0.278886,0.004305,0.058878,0.058446,0.109507,0.147054,0.0,0.0
659,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0

In [45]:
#user record df

In [46]:
user_sim_df= cs_p_df.loc[user_record_df['p_id']]
user_sim_df

,0,1,2,3,4,5,6,7,8,9,...,763,764,765,766,767,768,769,770,771,772
p_id,,,,,,,,,,,,,,,,,,,,,
213,0.613861,0.711183,0.792675,0.527619,0.672742,0.389970,0.725995,0.653622,0.729203,0.496400,...,0.572325,0.712884,0.786035,0.475522,0.574961,0.637621,0.181704,0.234124,0.644382,0.394316
309,0.150307,0.177126,0.182504,0.089523,0.048682,0.090859,0.106499,0.024429,0.000000,0.027914,...,0.144255,0.067570,0.081094,0.051261,0.107220,0.093096,0.289996,0.000868,0.042089,0.000802
659,0.565193,0.610689,0.647305,0.587127,0.465891,0.441940,0.520300,0.509067,0.435314,0.453518,...,0.531544,0.601432,0.611414,0.535693,0.326682,0.475744,0.193550,0.187874,0.454126,0.485166

In [47]:
 user_record_df=train_df.loc[train_df['u_id']==int(1567),:]
 user_record_df

      p_id  u_id  rating
6037   213  1567     3.0
6039   659  1567     5.0
6038   309  1567     0.0

In [48]:
user_sim_df= cs_u_df.loc[user_record_df['p_id']]
user_sim_df

,0,1,2,3,4,5,6,7,8,9,...,4171,4172,4173,4174,4175,4176,4177,4178,4179,4180
u_id,,,,,,,,,,,,,,,,,,,,,
213,0.066927,0.0,0.220906,0.427108,0.468874,0.088006,0.427993,0.494450,0.608624,0.315538,...,0.026379,0.336765,0.107697,0.009906,0.186498,0.059579,0.168317,0.229573,0.0,0.0
659,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
309,0.000000,0.0,0.111114,0.059549,0.185432,0.000000,0.028008,0.127028,0.168953,0.020912,...,0.022236,0.219540,0.278886,0.004305,0.058878,0.058446,0.109507,0.147054,0.0,0.0

In [49]:
user_rating_df = user_record_df[['rating']] 
user_rating_df

      rating
6037     3.0
6039     5.0
6038     0.0

In [50]:
#prediction

In [51]:
 prediction =np.matmul(user_sim_df.T.to_numpy() , user_rating_df.to_numpy()).flatten()
 prediction

array([0.20077963, 0.        , 0.66271752, ..., 0.68871893, 0.        ,
       0.        ])

In [58]:
result_df =pd.DataFrame()

for user_id in tqdm(all_userids):
  user_record_df = eat_review_mean.loc[eat_review_mean['u_id']==int(user_id),:] # (n,3) 

  user_sim_df= cs_p_df.loc[user_record_df['p_id']] #(n,1730). #1730개......##A
  user_rating_df = user_record_df[['rating']] #(n,1)##B
  sim_sum = np.sum(user_sim_df.T.to_numpy(),-1)


  prediction =np.matmul(user_sim_df.T.to_numpy() , user_rating_df.to_numpy()).flatten() /(sim_sum+1)##AB
  
  prediction_df = pd.DataFrame(prediction , index = cs_p_df.index).reset_index()
  prediction_df.columns=['p_id', 'pred_rating']
  prediction_df = prediction_df[['p_id', 'pred_rating']][prediction_df['p_id'].isin(test_df[test_df['u_id'] == user_id]['p_id'].values)]

  temp_df = prediction_df.merge(test_df[test_df['u_id'] == user_id], on='p_id')
  result_df = pd.concat([result_df, temp_df], axis=0)

100%|██████████| 4181/4181 [00:44<00:00, 94.47it/s]

In [60]:
len(userids)

NameError: ignored

In [61]:
result_df.head(10)

   p_id  pred_rating  u_id  rating
0   435     2.613249     0     3.5
1   472     2.397178     0     3.0
2   551     2.623225     0     3.0
3   633     2.417742     0     0.0
4   713     2.660198     0     3.0
0   315     0.000000     1     3.0
1   598     1.500000     1     3.0
0    95     3.704706     4     3.0
1    98     3.645573     4     5.0
2   238     3.668588     4     5.0

In [62]:
result_df.shape

(3201, 4)

In [63]:
result_df['pred_rating'].mean()

2.7742862387431213

In [64]:
result_df['rating'].mean()

3.878142247214412

In [65]:

mse = mean_squared_error(y_true=result_df['rating'].values, y_pred=result_df['pred_rating'].values)
rmse = np.sqrt(mse)

print(mse, rmse)

3.168861946000202 1.7801297553830737