In [31]:
import pandas as pd
import numpy as np
import math

In [32]:
# get size of vector
def mag(x):
    return math.sqrt(sum(i**2 for i in x))

In [33]:
res_matrix = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data/res_matrix.csv')
user_matrix = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data/user_matrix.csv')
group_count = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data/group_count.csv',names=['group','count'])

In [34]:

res_matrix.set_index('p_id', drop=True, inplace=True)
group_count.set_index('group', drop=True, inplace=True)

In [35]:
user_matrix.columns

Index(['Unnamed: 0', 'group_93', 'group_0', 'group_1', 'group_2', 'group_3',
       'group_4', 'group_5', 'group_6', 'group_7',
       ...
       'group_110', 'group_111', 'group_112', 'group_113', 'group_114',
       'group_115', 'group_116', 'group_117', 'group_118', 'group_119'],
      dtype='object', length=121)

In [36]:
user_matrix.rename(columns={'Unnamed: 0':'u_id'}, inplace=True)
# user_matrix.set_index('u_id', drop=True, inplace=True)

In [37]:
user_matrix

,u_id,group_93,group_0,group_1,group_2,group_3,group_4,group_5,group_6,group_7,...,group_110,group_111,group_112,group_113,group_114,group_115,group_116,group_117,group_118,group_119
0,715,2,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,1,0,1
1,453,2,0,2,4,2,4,16,0,0,...,4,2,4,0,1,0,5,0,0,0
2,1080,3,0,0,1,0,1,5,2,0,...,1,1,5,0,1,0,0,0,0,0
3,1479,3,0,0,2,0,0,1,1,1,...,0,0,0,0,1,0,1,0,0,0
4,954,19,0,6,3,3,6,22,3,5,...,3,2,4,0,14,0,3,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1725,537,0,0,0,0,0,0,1,0,0,...,0,0,0,0,1,0,0,0,0,0
1726,1597,2,0,0,0,0,1,2,2,0,...,0,1,0,0,0,0,2,0,0,0
1727,603,1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,1,1,0,0,0
1728,655,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1729,58,1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [38]:
user_matrix.set_index('u_id', drop=True, inplace=True)

In [39]:
user_matrix

,group_93,group_0,group_1,group_2,group_3,group_4,group_5,group_6,group_7,group_8,...,group_110,group_111,group_112,group_113,group_114,group_115,group_116,group_117,group_118,group_119
u_id,,,,,,,,,,,,,,,,,,,,,
715,2,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,1
453,2,0,2,4,2,4,16,0,0,0,...,4,2,4,0,1,0,5,0,0,0
1080,3,0,0,1,0,1,5,2,0,0,...,1,1,5,0,1,0,0,0,0,0
1479,3,0,0,2,0,0,1,1,1,0,...,0,0,0,0,1,0,1,0,0,0
954,19,0,6,3,3,6,22,3,5,0,...,3,2,4,0,14,0,3,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
537,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,0,0
1597,2,0,0,0,0,1,2,2,0,0,...,0,1,0,0,0,0,2,0,0,0
603,1,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,1,1,0,0,0
655,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
58,1,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [40]:
res_matrix

,group_93,group_0,group_1,group_2,group_3,group_4,group_5,group_6,group_7,group_8,...,group_110,group_111,group_112,group_113,group_114,group_115,group_116,group_117,group_118,group_119
p_id,,,,,,,,,,,,,,,,,,,,,
553,143,0,2,75,19,29,7,18,9,0,...,2,11,21,0,35,10,16,5,3,9
383,103,0,13,11,25,11,79,11,9,1,...,7,7,17,0,22,6,17,3,0,4
78,23,0,5,3,4,5,33,1,2,1,...,2,5,1,0,9,1,5,1,0,0
715,30,0,2,5,3,7,66,3,3,1,...,3,3,11,0,11,3,2,1,2,2
45,5,0,0,3,0,2,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225,9,0,0,1,8,3,21,1,0,1,...,1,2,2,0,5,0,6,2,0,0
81,6,0,1,3,2,3,32,2,0,0,...,0,1,1,0,5,1,7,0,0,0
215,2,0,0,1,1,0,1,0,1,0,...,0,0,1,0,1,0,1,0,0,0
270,3,0,0,0,0,0,1,0,1,0,...,0,0,0,0,1,0,0,0,0,0
760,0,0,0,0,0,0,3,0,0,0,...,0,0,0,0,2,1,0,0,0,1

In [41]:
user_matrix

,group_93,group_0,group_1,group_2,group_3,group_4,group_5,group_6,group_7,group_8,...,group_110,group_111,group_112,group_113,group_114,group_115,group_116,group_117,group_118,group_119
u_id,,,,,,,,,,,,,,,,,,,,,
715,2,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,1
453,2,0,2,4,2,4,16,0,0,0,...,4,2,4,0,1,0,5,0,0,0
1080,3,0,0,1,0,1,5,2,0,0,...,1,1,5,0,1,0,0,0,0,0
1479,3,0,0,2,0,0,1,1,1,0,...,0,0,0,0,1,0,1,0,0,0
954,19,0,6,3,3,6,22,3,5,0,...,3,2,4,0,14,0,3,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
537,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,0,0
1597,2,0,0,0,0,1,2,2,0,0,...,0,1,0,0,0,0,2,0,0,0
603,1,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,1,1,0,0,0
655,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
58,1,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [42]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [43]:
user_matrix

,group_93,group_0,group_1,group_2,group_3,group_4,group_5,group_6,group_7,group_8,...,group_110,group_111,group_112,group_113,group_114,group_115,group_116,group_117,group_118,group_119
u_id,,,,,,,,,,,,,,,,,,,,,
715,2,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,1
453,2,0,2,4,2,4,16,0,0,0,...,4,2,4,0,1,0,5,0,0,0
1080,3,0,0,1,0,1,5,2,0,0,...,1,1,5,0,1,0,0,0,0,0
1479,3,0,0,2,0,0,1,1,1,0,...,0,0,0,0,1,0,1,0,0,0
954,19,0,6,3,3,6,22,3,5,0,...,3,2,4,0,14,0,3,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
537,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,0,0
1597,2,0,0,0,0,1,2,2,0,0,...,0,1,0,0,0,0,2,0,0,0
603,1,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,1,1,0,0,0
655,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
58,1,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [44]:
res_matrix

,group_93,group_0,group_1,group_2,group_3,group_4,group_5,group_6,group_7,group_8,...,group_110,group_111,group_112,group_113,group_114,group_115,group_116,group_117,group_118,group_119
p_id,,,,,,,,,,,,,,,,,,,,,
553,143,0,2,75,19,29,7,18,9,0,...,2,11,21,0,35,10,16,5,3,9
383,103,0,13,11,25,11,79,11,9,1,...,7,7,17,0,22,6,17,3,0,4
78,23,0,5,3,4,5,33,1,2,1,...,2,5,1,0,9,1,5,1,0,0
715,30,0,2,5,3,7,66,3,3,1,...,3,3,11,0,11,3,2,1,2,2
45,5,0,0,3,0,2,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225,9,0,0,1,8,3,21,1,0,1,...,1,2,2,0,5,0,6,2,0,0
81,6,0,1,3,2,3,32,2,0,0,...,0,1,1,0,5,1,7,0,0,0
215,2,0,0,1,1,0,1,0,1,0,...,0,0,1,0,1,0,1,0,0,0
270,3,0,0,0,0,0,1,0,1,0,...,0,0,0,0,1,0,0,0,0,0
760,0,0,0,0,0,0,3,0,0,0,...,0,0,0,0,2,1,0,0,0,1

In [54]:
group_count.head()

          count
group
NaN           0
group_93    857
group_0       4
group_1      48
group_2     129

In [57]:
p_m = pd.DataFrame(np.array(res_matrix) * (1/np.array(group_count['count'])), index=res_matrix.index)
p_m = p_m.iloc[:,:].div(p_m.sum(axis=1), axis=0).fillna(0)
u_m = pd.DataFrame(np.array(user_matrix) * (1/np.array(group_count['count'])), index=user_matrix.index)
u_m = u_m.iloc[:,:].div(u_m.sum(axis=1), axis=0).fillna(0)

In [58]:
p_m

,0,1,2,3,4,5,6,7,8,9,...,110,111,112,113,114,115,116,117,118,119
p_id,,,,,,,,,,,,,,,,,,,,,
553,0.004189,0.0,0.001046,0.014595,0.004586,0.003021,0.002978,0.011021,0.006276,0.000000,...,0.002391,0.003586,0.003254,0.0,0.003207,0.010041,0.006925,0.041839,0.004430,0.004430
383,0.003020,0.0,0.006805,0.002143,0.006040,0.001147,0.033644,0.006741,0.006282,0.002792,...,0.008376,0.002284,0.002637,0.0,0.002017,0.006030,0.007365,0.025127,0.000000,0.001971
78,0.002676,0.0,0.010387,0.002319,0.003835,0.002069,0.055770,0.002432,0.005539,0.011079,...,0.009496,0.006475,0.000615,0.0,0.003275,0.003988,0.008596,0.033237,0.000000,0.000000
715,0.002010,0.0,0.002393,0.002226,0.001657,0.001668,0.064242,0.004202,0.004786,0.006381,...,0.008204,0.002237,0.003899,0.0,0.002306,0.006891,0.001980,0.019143,0.006756,0.002252
45,0.002587,0.0,0.000000,0.010312,0.000000,0.003680,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.005759,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225,0.002642,0.0,0.000000,0.001950,0.019353,0.003132,0.089549,0.006136,0.000000,0.027954,...,0.011980,0.006535,0.003106,0.0,0.004591,0.000000,0.026027,0.167726,0.000000,0.000000
81,0.002224,0.0,0.006618,0.007388,0.006109,0.003954,0.172296,0.015496,0.000000,0.000000,...,0.000000,0.004126,0.001961,0.0,0.005797,0.012707,0.038340,0.000000,0.000000,0.000000
215,0.002088,0.0,0.000000,0.006935,0.008602,0.000000,0.015163,0.000000,0.024850,0.000000,...,0.000000,0.000000,0.005522,0.0,0.003265,0.000000,0.015424,0.000000,0.000000,0.000000
270,0.017691,0.0,0.000000,0.000000,0.000000,0.000000,0.085657,0.000000,0.140382,0.000000,...,0.000000,0.000000,0.000000,0.0,0.018444,0.000000,0.000000,0.000000,0.000000,0.000000
760,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.130582,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.018745,0.102724,0.000000,0.000000,0.000000,0.050355

In [59]:
u_m

,0,1,2,3,4,5,6,7,8,9,...,110,111,112,113,114,115,116,117,118,119
u_id,,,,,,,,,,,,,,,,,,,,,
715,0.003708,0.0,0.000000,0.000000,0.000000,0.006593,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.529628,0.0,0.031155
453,0.000399,0.0,0.007130,0.005306,0.003291,0.002840,0.046403,0.000000,0.000000,0.0,...,0.032592,0.004444,0.004225,0.0,0.000624,0.000000,0.014751,0.000000,0.0,0.000000
1080,0.001781,0.0,0.000000,0.003944,0.000000,0.002111,0.043114,0.024817,0.000000,0.0,...,0.024226,0.006607,0.015702,0.0,0.001857,0.000000,0.000000,0.000000,0.0,0.000000
1479,0.002209,0.0,0.000000,0.009783,0.000000,0.000000,0.010694,0.015390,0.017527,0.0,...,0.000000,0.000000,0.000000,0.0,0.002303,0.000000,0.010879,0.000000,0.0,0.000000
954,0.001906,0.0,0.010748,0.002000,0.002480,0.002141,0.032061,0.006291,0.011942,0.0,...,0.012283,0.002233,0.002123,0.0,0.004393,0.000000,0.004447,0.028661,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
537,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.366549,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.0,0.078928,0.000000,0.000000,0.000000,0.0,0.000000
1597,0.006059,0.0,0.000000,0.000000,0.000000,0.010774,0.088014,0.126655,0.000000,0.0,...,0.000000,0.033720,0.000000,0.0,0.000000,0.000000,0.089532,0.000000,0.0,0.000000
603,0.003497,0.0,0.000000,0.000000,0.000000,0.000000,0.050797,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.0,0.000000,0.119881,0.051673,0.000000,0.0,0.000000
655,0.007016,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
58,0.004087,0.0,0.000000,0.000000,0.000000,0.000000,0.059367,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000

In [60]:
p_m.to_csv('/content/drive/MyDrive/Colab Notebooks/data/normalized_item_matrix.csv')
u_m.to_csv('/content/drive/MyDrive/Colab Notebooks/data/normalized_user_matrix.csv')