In [1]:
import pandas as pd
import numpy as np
import math

In [2]:
# get size of vector
def mag(x):
    return math.sqrt(sum(i**2 for i in x))

In [5]:
res_matrix = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data/강남구_cafe_res_matrix.csv')
user_matrix = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data/강남구_cafe_user_matrix.csv')
group_count = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data/강남구_cafe_group_count.csv',names=['group','count'])

In [6]:
res_matrix

,Unnamed: 0,group_21,group_0,group_1,group_2,group_3,group_4,group_5,group_6,group_7,...,group_110,group_111,group_112,group_113,group_114,group_115,group_116,group_117,group_118,group_119
0,0,160,22,11,22,19,3,5,13,7,...,3,0,19,31,29,7,2,5,2,2
1,1,19,2,1,4,1,0,0,0,0,...,0,0,2,1,2,4,0,0,0,0
2,2,0,7,5,1,0,0,0,0,2,...,0,0,1,1,1,1,0,0,0,0
3,3,45,9,4,9,10,0,0,3,5,...,0,1,1,12,7,3,0,0,0,0
4,4,43,4,2,51,6,0,0,1,0,...,0,0,4,0,15,0,2,2,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
869,869,3,1,4,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
870,870,4,4,6,4,9,0,0,0,0,...,0,0,2,1,1,1,0,0,0,0
871,871,25,11,2,4,5,2,0,2,1,...,0,0,5,6,9,5,0,0,0,0
872,872,1,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
873,873,37,5,10,8,6,10,0,3,42,...,1,1,10,4,5,9,0,0,0,1

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [7]:
group_count.drop([0], inplace =True)

In [8]:
res_matrix.rename(columns={'Unnamed: 0':'p_id'}, inplace=True)
res_matrix.set_index('p_id', drop=True, inplace=True)
group_count.set_index('group', drop=True, inplace=True)

In [9]:
user_matrix

,Unnamed: 0,group_21,group_0,group_1,group_2,group_3,group_4,group_5,group_6,group_7,...,group_110,group_111,group_112,group_113,group_114,group_115,group_116,group_117,group_118,group_119
0,2182,8,3,3,1,1,0,0,0,2,...,1,0,0,0,0,0,0,0,0,0
1,1863,27,20,8,4,5,10,2,6,1,...,1,1,10,1,5,3,0,1,0,0
2,1296,0,0,0,2,1,0,0,0,0,...,0,0,3,0,1,0,0,0,0,0
3,1185,0,0,0,0,0,0,0,0,0,...,0,0,0,1,1,0,0,0,0,0
4,1700,10,4,0,2,2,1,0,0,3,...,0,0,1,6,4,3,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2583,2011,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2584,2390,1,1,0,0,1,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
2585,145,1,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
2586,541,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2587,900,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [10]:
user_matrix.rename(columns={'Unnamed: 0':'u_id'}, inplace=True)
# user_matrix.set_index('u_id', drop=True, inplace=True)

In [11]:
user_matrix

,u_id,group_21,group_0,group_1,group_2,group_3,group_4,group_5,group_6,group_7,...,group_110,group_111,group_112,group_113,group_114,group_115,group_116,group_117,group_118,group_119
0,2182,8,3,3,1,1,0,0,0,2,...,1,0,0,0,0,0,0,0,0,0
1,1863,27,20,8,4,5,10,2,6,1,...,1,1,10,1,5,3,0,1,0,0
2,1296,0,0,0,2,1,0,0,0,0,...,0,0,3,0,1,0,0,0,0,0
3,1185,0,0,0,0,0,0,0,0,0,...,0,0,0,1,1,0,0,0,0,0
4,1700,10,4,0,2,2,1,0,0,3,...,0,0,1,6,4,3,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2583,2011,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2584,2390,1,1,0,0,1,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
2585,145,1,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
2586,541,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2587,900,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [12]:
user_matrix.set_index('u_id', drop=True, inplace=True)

In [13]:
user_matrix

,group_21,group_0,group_1,group_2,group_3,group_4,group_5,group_6,group_7,group_8,...,group_110,group_111,group_112,group_113,group_114,group_115,group_116,group_117,group_118,group_119
u_id,,,,,,,,,,,,,,,,,,,,,
2182,8,3,3,1,1,0,0,0,2,0,...,1,0,0,0,0,0,0,0,0,0
1863,27,20,8,4,5,10,2,6,1,0,...,1,1,10,1,5,3,0,1,0,0
1296,0,0,0,2,1,0,0,0,0,0,...,0,0,3,0,1,0,0,0,0,0
1185,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,1,0,0,0,0,0
1700,10,4,0,2,2,1,0,0,3,0,...,0,0,1,6,4,3,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2011,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2390,1,1,0,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
145,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
541,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
900,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [14]:
res_matrix

,group_21,group_0,group_1,group_2,group_3,group_4,group_5,group_6,group_7,group_8,...,group_110,group_111,group_112,group_113,group_114,group_115,group_116,group_117,group_118,group_119
p_id,,,,,,,,,,,,,,,,,,,,,
0,160,22,11,22,19,3,5,13,7,0,...,3,0,19,31,29,7,2,5,2,2
1,19,2,1,4,1,0,0,0,0,0,...,0,0,2,1,2,4,0,0,0,0
2,0,7,5,1,0,0,0,0,2,0,...,0,0,1,1,1,1,0,0,0,0
3,45,9,4,9,10,0,0,3,5,0,...,0,1,1,12,7,3,0,0,0,0
4,43,4,2,51,6,0,0,1,0,5,...,0,0,4,0,15,0,2,2,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
869,3,1,4,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
870,4,4,6,4,9,0,0,0,0,0,...,0,0,2,1,1,1,0,0,0,0
871,25,11,2,4,5,2,0,2,1,0,...,0,0,5,6,9,5,0,0,0,0
872,1,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
873,37,5,10,8,6,10,0,3,42,0,...,1,1,10,4,5,9,0,0,0,1

In [15]:
group_count.head()

          count
group
group_21   1110
group_0      78
group_1      20
group_2     158
group_3     189

In [16]:
p_m = pd.DataFrame(np.array(res_matrix) * (1/np.array(group_count['count'])), index=res_matrix.index)
p_m = p_m.iloc[:,:].div(p_m.sum(axis=1), axis=0).fillna(0)
u_m = pd.DataFrame(np.array(user_matrix) * (1/np.array(group_count['count'])), index=user_matrix.index)
u_m = u_m.iloc[:,:].div(u_m.sum(axis=1), axis=0).fillna(0)

In [17]:
p_m

,0,1,2,3,4,5,6,7,8,9,...,110,111,112,113,114,115,116,117,118,119
p_id,,,,,,,,,,,,,,,,,,,,,
0,0.002779,0.005437,0.010603,0.002684,0.001938,0.001205,0.003012,0.003978,0.003969,0.000000,...,0.019278,0.000000,0.005159,0.028457,0.005947,0.002546,0.001483,0.032129,0.009639,0.004819
1,0.003729,0.005585,0.010891,0.005515,0.001153,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.006136,0.010373,0.004635,0.016440,0.000000,0.000000,0.000000,0.000000
2,0.000000,0.022221,0.061902,0.001567,0.000000,0.000000,0.000000,0.000000,0.014565,0.000000,...,0.000000,0.000000,0.003487,0.011791,0.002634,0.004672,0.000000,0.000000,0.000000,0.000000
3,0.002907,0.008275,0.014343,0.004085,0.003795,0.000000,0.000000,0.003415,0.010547,0.000000,...,0.000000,0.011953,0.001010,0.040981,0.005341,0.004059,0.000000,0.000000,0.000000,0.000000
4,0.002041,0.002702,0.005269,0.017006,0.001673,0.000000,0.000000,0.000836,0.000000,0.263426,...,0.000000,0.000000,0.002968,0.000000,0.008407,0.000000,0.004053,0.035123,0.000000,0.006586
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
869,0.003407,0.016163,0.252137,0.007979,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
870,0.001050,0.014939,0.087393,0.007375,0.013872,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.008206,0.013872,0.003099,0.005496,0.000000,0.000000,0.000000,0.000000
871,0.004279,0.026792,0.018998,0.004810,0.005026,0.007916,0.000000,0.006031,0.005588,0.000000,...,0.000000,0.000000,0.013379,0.054280,0.018189,0.017923,0.000000,0.000000,0.000000,0.000000
872,0.001190,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.062914,0.000000,0.000000,0.000000,0.440395,0.000000,0.000000
873,0.002079,0.003998,0.031187,0.003158,0.001980,0.012995,0.000000,0.002970,0.077051,0.000000,...,0.020792,0.010396,0.008785,0.011881,0.003318,0.010592,0.000000,0.000000,0.000000,0.007797

In [18]:
u_m

,0,1,2,3,4,5,6,7,8,9,...,110,111,112,113,114,115,116,117,118,119
u_id,,,,,,,,,,,,,,,,,,,,,
2182,0.002531,0.013507,0.052677,0.002223,0.001858,0.000000,0.000000,0.000000,0.020658,0.0,...,0.117061,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.00000,0.0,0.0
1863,0.002523,0.026593,0.041484,0.002626,0.002744,0.021606,0.006482,0.009877,0.003050,0.0,...,0.034570,0.017285,0.014607,0.004939,0.005517,0.005870,0.0,0.03457,0.0,0.0
1296,0.000000,0.000000,0.000000,0.019220,0.008034,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,0.064158,0.000000,0.016153,0.000000,0.0,0.00000,0.0,0.0
1185,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.102092,0.022808,0.000000,0.0,0.00000,0.0,0.0
1700,0.002504,0.014255,0.000000,0.003519,0.002942,0.005791,0.000000,0.000000,0.024527,0.0,...,0.000000,0.000000,0.003915,0.079422,0.011829,0.015734,0.0,0.00000,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2011,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.00000,0.0,0.0
2390,0.003134,0.044605,0.000000,0.000000,0.018409,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,0.049003,0.000000,0.000000,0.000000,0.0,0.00000,0.0,0.0
145,0.078073,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.000000,0.921927,0.000000,0.0,0.00000,0.0,0.0
541,0.057132,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.00000,0.0,0.0
900,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.00000,0.0,0.0

In [19]:
p_m.to_csv('/content/drive/MyDrive/Colab Notebooks/data/강남구_cafe_normalized_item_matrix.csv')
u_m.to_csv('/content/drive/MyDrive/Colab Notebooks/data/강남구_cafe_normalized_user_matrix.csv')

In [20]:
group_count.to_csv('/content/drive/MyDrive/Colab Notebooks/data/강남구_cafe_group_count.csv')