In [1]:
import pandas as pd
import numpy as np
import math

In [2]:
# get size of vector
def mag(x):
    return math.sqrt(sum(i**2 for i in x))

In [62]:
res_matrix = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data/광진구_cafe_res_matrix.csv')
user_matrix = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data/광진구_cafe_user_matrix.csv')
group_count = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data/광진구_cafe_group_count.csv',names=['group','count'])

In [63]:
res_matrix

,Unnamed: 0,group_40,group_0,group_1,group_2,group_3,group_4,group_5,group_6,group_7,...,group_110,group_111,group_112,group_113,group_114,group_115,group_116,group_117,group_118,group_119
0,0,76,33,15,11,150,0,8,0,17,...,0,7,0,3,0,0,0,1,0,0
1,1,7,4,0,1,15,0,2,0,4,...,1,0,0,0,3,0,0,0,0,0
2,2,20,2,9,2,44,1,2,0,4,...,1,2,0,1,0,0,0,1,1,0
3,3,19,1,2,1,38,0,0,0,2,...,1,2,0,0,0,0,0,0,0,0
4,4,31,3,83,6,71,0,2,1,5,...,0,3,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146,146,5,0,0,0,11,0,0,0,3,...,0,0,0,0,0,0,0,0,0,0
147,147,21,0,7,2,50,0,2,0,8,...,0,2,0,0,0,0,1,0,0,0
148,148,4,0,5,0,24,0,1,0,7,...,0,0,0,1,0,0,1,0,1,0
149,149,1,1,0,0,8,0,0,0,2,...,0,1,0,0,0,0,0,0,0,0
150,150,1,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [64]:
group_count.drop([0], inplace =True)

In [65]:
res_matrix.rename(columns={'Unnamed: 0':'p_id'}, inplace=True)
res_matrix.set_index('p_id', drop=True, inplace=True)
group_count.set_index('group', drop=True, inplace=True)

In [66]:
user_matrix

,Unnamed: 0,group_40,group_0,group_1,group_2,group_3,group_4,group_5,group_6,group_7,...,group_110,group_111,group_112,group_113,group_114,group_115,group_116,group_117,group_118,group_119
0,416,2,0,1,1,2,0,0,0,3,...,0,1,0,0,0,0,0,0,0,0
1,252,57,13,36,17,107,0,10,0,9,...,0,1,0,4,0,0,2,0,1,0
2,148,29,0,3,0,109,0,5,0,9,...,0,1,0,0,0,0,0,0,0,0
3,266,1,1,0,0,1,0,0,0,1,...,0,0,1,1,0,0,0,0,0,0
4,406,0,0,2,0,9,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,10,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
596,372,0,0,0,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
597,342,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
598,87,2,0,0,0,3,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
599,367,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [67]:
user_matrix.rename(columns={'Unnamed: 0':'u_id'}, inplace=True)
# user_matrix.set_index('u_id', drop=True, inplace=True)

In [68]:
user_matrix

,u_id,group_40,group_0,group_1,group_2,group_3,group_4,group_5,group_6,group_7,...,group_110,group_111,group_112,group_113,group_114,group_115,group_116,group_117,group_118,group_119
0,416,2,0,1,1,2,0,0,0,3,...,0,1,0,0,0,0,0,0,0,0
1,252,57,13,36,17,107,0,10,0,9,...,0,1,0,4,0,0,2,0,1,0
2,148,29,0,3,0,109,0,5,0,9,...,0,1,0,0,0,0,0,0,0,0
3,266,1,1,0,0,1,0,0,0,1,...,0,0,1,1,0,0,0,0,0,0
4,406,0,0,2,0,9,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,10,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
596,372,0,0,0,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
597,342,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
598,87,2,0,0,0,3,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
599,367,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [69]:
user_matrix.set_index('u_id', drop=True, inplace=True)

In [70]:
user_matrix

,group_40,group_0,group_1,group_2,group_3,group_4,group_5,group_6,group_7,group_8,...,group_110,group_111,group_112,group_113,group_114,group_115,group_116,group_117,group_118,group_119
u_id,,,,,,,,,,,,,,,,,,,,,
416,2,0,1,1,2,0,0,0,3,0,...,0,1,0,0,0,0,0,0,0,0
252,57,13,36,17,107,0,10,0,9,0,...,0,1,0,4,0,0,2,0,1,0
148,29,0,3,0,109,0,5,0,9,0,...,0,1,0,0,0,0,0,0,0,0
266,1,1,0,0,1,0,0,0,1,0,...,0,0,1,1,0,0,0,0,0,0
406,0,0,2,0,9,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
372,0,0,0,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
342,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
87,2,0,0,0,3,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
367,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [71]:
res_matrix

,group_40,group_0,group_1,group_2,group_3,group_4,group_5,group_6,group_7,group_8,...,group_110,group_111,group_112,group_113,group_114,group_115,group_116,group_117,group_118,group_119
p_id,,,,,,,,,,,,,,,,,,,,,
0,76,33,15,11,150,0,8,0,17,0,...,0,7,0,3,0,0,0,1,0,0
1,7,4,0,1,15,0,2,0,4,0,...,1,0,0,0,3,0,0,0,0,0
2,20,2,9,2,44,1,2,0,4,0,...,1,2,0,1,0,0,0,1,1,0
3,19,1,2,1,38,0,0,0,2,0,...,1,2,0,0,0,0,0,0,0,0
4,31,3,83,6,71,0,2,1,5,0,...,0,3,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146,5,0,0,0,11,0,0,0,3,0,...,0,0,0,0,0,0,0,0,0,0
147,21,0,7,2,50,0,2,0,8,0,...,0,2,0,0,0,0,1,0,0,0
148,4,0,5,0,24,0,1,0,7,0,...,0,0,0,1,0,0,1,0,1,0
149,1,1,0,0,8,0,0,0,2,0,...,0,1,0,0,0,0,0,0,0,0
150,1,0,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [72]:
group_count.head()

          count
group
group_40    507
group_0      35
group_1      39
group_2      44
group_3      97

In [73]:
p_m = pd.DataFrame(np.array(res_matrix) * (1/np.array(group_count['count'])), index=res_matrix.index)
p_m = p_m.iloc[:,:].div(p_m.sum(axis=1), axis=0).fillna(0)
u_m = pd.DataFrame(np.array(user_matrix) * (1/np.array(group_count['count'])), index=user_matrix.index)
u_m = u_m.iloc[:,:].div(u_m.sum(axis=1), axis=0).fillna(0)

In [74]:
p_m

,0,1,2,3,4,5,6,7,8,9,...,110,111,112,113,114,115,116,117,118,119
p_id,,,,,,,,,,,,,,,,,,,,,
0,0.003599,0.022637,0.009234,0.006002,0.037127,0.000000,0.003149,0.00000,0.007288,0.0,...,0.000000,0.008845,0.0,0.006002,0.000000,0.0,0.000000,0.002183,0.000000,0.0
1,0.005589,0.046260,0.000000,0.009199,0.062595,0.000000,0.013271,0.00000,0.028913,0.0,...,0.017599,0.000000,0.0,0.000000,0.404778,0.0,0.000000,0.000000,0.000000,0.0
2,0.003686,0.005339,0.021563,0.004247,0.042386,0.031147,0.003064,0.00000,0.006674,0.0,...,0.004063,0.009836,0.0,0.007787,0.000000,0.0,0.000000,0.008495,0.046720,0.0
3,0.004275,0.003259,0.005850,0.002593,0.044691,0.000000,0.000000,0.00000,0.004074,0.0,...,0.004960,0.012008,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0
4,0.002944,0.004127,0.102477,0.006566,0.035245,0.000000,0.001579,0.00963,0.004299,0.0,...,0.000000,0.007603,0.0,0.004013,0.000000,0.0,0.000000,0.000000,0.024076,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146,0.005923,0.000000,0.000000,0.000000,0.068113,0.000000,0.000000,0.00000,0.032177,0.0,...,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0
147,0.005234,0.000000,0.022679,0.005743,0.065132,0.000000,0.004143,0.00000,0.018051,0.0,...,0.000000,0.013301,0.0,0.000000,0.000000,0.0,0.011487,0.000000,0.000000,0.0
148,0.001392,0.000000,0.022614,0.000000,0.043642,0.000000,0.002892,0.00000,0.022049,0.0,...,0.000000,0.000000,0.0,0.014699,0.000000,0.0,0.016035,0.000000,0.088194,0.0
149,0.002973,0.043060,0.000000,0.000000,0.124297,0.000000,0.000000,0.00000,0.053825,0.0,...,0.000000,0.079321,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0
150,0.008298,0.000000,0.107878,0.000000,0.043374,0.000000,0.000000,0.00000,0.000000,0.0,...,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0

In [75]:
u_m

,0,1,2,3,4,5,6,7,8,9,...,110,111,112,113,114,115,116,117,118,119
u_id,,,,,,,,,,,,,,,,,,,,,
416,0.003284,0.000000,0.021344,0.018918,0.017163,0.0,0.000000,0.0,0.044594,0.0,...,0.0,0.043811,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0
252,0.006868,0.022691,0.056393,0.023604,0.067390,0.0,0.010015,0.0,0.009818,0.0,...,0.0,0.003215,0.000000,0.020364,0.0,0.0,0.011108,0.0,0.030546,0.0
148,0.004600,0.000000,0.006186,0.000000,0.090360,0.0,0.006591,0.0,0.012923,0.0,...,0.0,0.004232,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0
266,0.001204,0.017447,0.000000,0.000000,0.006295,0.0,0.000000,0.0,0.010904,0.0,...,0.0,0.000000,0.610649,0.050887,0.0,0.0,0.000000,0.0,0.000000,0.0
406,0.000000,0.000000,0.195606,0.000000,0.353906,0.0,0.000000,0.0,0.000000,0.0,...,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,...,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0
372,0.000000,0.000000,0.000000,0.000000,0.059541,0.0,0.000000,0.0,0.103134,0.0,...,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0
342,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.092253,0.0,...,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0
87,0.002404,0.000000,0.000000,0.000000,0.018846,0.0,0.000000,0.0,0.000000,0.0,...,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0
367,0.016091,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,...,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.000000,0.0

In [76]:
p_m.to_csv('/content/drive/MyDrive/Colab Notebooks/data/광진구_cafe_normalized_item_matrix.csv')
u_m.to_csv('/content/drive/MyDrive/Colab Notebooks/data/광진구_cafe_normalized_user_matrix.csv')

In [77]:
group_count.to_csv('/content/drive/MyDrive/Colab Notebooks/data/광진구_cafe_group_count.csv')