In [5]:
import pandas as pd
import numpy as np
import math
from tqdm import tqdm

In [6]:
# get size of vector
def mag(x):
    return math.sqrt(sum(i**2 for i in x))

In [95]:
p_m = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data/광진구_cafe_normalized_item_matrix.csv')
u_m = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data/광진구_cafe_normalized_user_matrix.csv')
group_count = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data/광진구_cafe_group_count.csv')

# res_matrix.rename(columns ={'Unnamed: 0':'p_id' }, inplace =True)
p_m.set_index('p_id', inplace =True)
# user_matrix.rename(columns ={'Unnamed: 0':'u_id' }, inplace =True)
u_m.set_index('u_id', inplace =True)
# group_count.rename(columns ={'Unnamed: 0':'group' }, inplace =True)
# group_count.set_index('group', inplace =True)
# res_matrix.set_index('p_id', drop=True, inplace=True)
# user_matrix.set_index('u_id', drop=True, inplace=True)
# group_count.set_index('group', drop=True, inplace=True)

In [96]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [97]:
group_count

         group  count
0      group_0   1003
1      group_1    106
2      group_2     30
3      group_3      1
4      group_4     24
..         ...    ...
115  group_115     72
116  group_116      3
117  group_117      4
118  group_118     35
119  group_119     33

[120 rows x 2 columns]

In [98]:
group_count.set_index('group', inplace =True)

In [99]:
group_count

           count
group
group_0     1003
group_1      106
group_2       30
group_3        1
group_4       24
...          ...
group_115     72
group_116      3
group_117      4
group_118     35
group_119     33

[120 rows x 1 columns]

In [100]:
p_m

,0,1,2,3,4,5,6,7,8,9,...,110,111,112,113,114,115,116,117,118,119
p_id,,,,,,,,,,,,,,,,,,,,,
0,0.004348,0.010702,0.007090,0.000000,0.004431,0.010684,0.003324,0.005065,0.009669,0.004924,...,0.000000,0.006862,0.000000,0.0,0.008103,0.003939,0.0,0.000000,0.009116,0.006446
1,0.003300,0.006361,0.006130,0.000000,0.005108,0.002939,0.003831,0.000000,0.009288,0.003406,...,0.030651,0.002966,0.030651,0.0,0.084070,0.002129,0.0,0.007663,0.005254,0.013932
2,0.003648,0.003699,0.000000,0.000000,0.000000,0.010741,0.004084,0.006223,0.019801,0.003630,...,0.000000,0.000000,0.000000,0.0,0.007468,0.014521,0.0,0.000000,0.000000,0.007920
3,0.003256,0.006847,0.000000,0.090726,0.000000,0.004971,0.000000,0.012961,0.005499,0.000000,...,0.000000,0.005853,0.000000,0.0,0.005184,0.005040,0.0,0.000000,0.005184,0.005499
4,0.005337,0.000000,0.029738,0.000000,0.000000,0.012221,0.000000,0.000000,0.027035,0.024782,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
668,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
669,0.003294,0.006235,0.000000,0.000000,0.000000,0.000000,0.000000,0.015735,0.040053,0.000000,...,0.000000,0.000000,0.000000,0.0,0.009441,0.009179,0.0,0.000000,0.009441,0.030039
670,0.001945,0.004601,0.008128,0.000000,0.000000,0.006681,0.000000,0.011611,0.007389,0.000000,...,0.000000,0.007866,0.000000,0.0,0.000000,0.003387,0.0,0.000000,0.006967,0.036946
671,0.004011,0.009488,0.000000,0.000000,0.000000,0.013777,0.000000,0.000000,0.060951,0.000000,...,0.000000,0.032442,0.000000,0.0,0.057468,0.055872,0.0,0.000000,0.000000,0.060951
672,0.019370,0.091640,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000

In [101]:
u_m

,0,1,2,3,4,5,6,7,8,9,...,110,111,112,113,114,115,116,117,118,119
u_id,,,,,,,,,,,,,,,,,,,,,
416,0.006625,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.210944,0.000000,0.000000,...,0.0,0.071449,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000
252,0.004064,0.005728,0.000000,0.0,0.0,0.010694,0.005421,0.012391,0.013142,0.014456,...,0.0,0.002798,0.0,0.0,0.0,0.048188,0.0,0.0,0.0,0.028913
148,0.004666,0.001698,0.017998,0.0,0.0,0.000000,0.011249,0.000000,0.000000,0.000000,...,0.0,0.000000,0.0,0.0,0.0,0.012499,0.0,0.0,0.0,0.010908
266,0.002289,0.000000,0.000000,0.0,0.0,0.000000,0.071732,0.109306,0.000000,0.000000,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000
406,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.000000,0.0,0.0,0.0,0.055113,0.0,0.0,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000
372,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000
342,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000
87,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000
367,0.005725,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.521974

In [102]:
from sklearn.metrics.pairwise import cosine_similarity

def cos_sim_matrix(a,b):
  cos_sim=cosine_similarity(a,b)
  result_df =pd.DataFrame(data=cos_sim, index=[a.index])

  return result_df

In [103]:
#similarity df

In [104]:

cs_u_df = cos_sim_matrix(u_m,u_m)
cs_u_df.head()

,0,1,2,3,4,5,6,7,8,9,...,590,591,592,593,594,595,596,597,598,599
u_id,,,,,,,,,,,,,,,,,,,,,
416,1.000000,0.186652,0.176435,0.267409,0.158785,0.0,0.092505,0.130909,0.085458,0.265606,...,0.219197,0.0,0.078885,0.078064,0.073280,0.0,0.170740,0.126436,0.509381,0.000163
252,0.186652,1.000000,0.803434,0.138348,0.562621,0.0,0.448050,0.805298,0.232335,0.421352,...,0.295331,0.0,0.318213,0.053770,0.077065,0.0,0.254995,0.111052,0.206147,0.133786
148,0.176435,0.803434,1.000000,0.096126,0.722041,0.0,0.447382,0.762988,0.191736,0.409751,...,0.259275,0.0,0.292243,0.048856,0.020501,0.0,0.267399,0.111259,0.265142,0.051538
266,0.267409,0.138348,0.096126,1.000000,0.113349,0.0,0.087607,0.090043,0.102448,0.145297,...,0.051640,0.0,0.102539,0.027730,0.074116,0.0,0.074284,0.031970,0.075740,0.000055
406,0.158785,0.562621,0.722041,0.113349,1.000000,0.0,0.531280,0.353325,0.246862,0.473940,...,0.313460,0.0,0.292986,0.054787,0.092794,0.0,0.248156,0.000000,0.310389,0.000000

In [105]:
cs_p_df = cos_sim_matrix(p_m,p_m)
cs_p_df.head()

,0,1,2,3,4,5,6,7,8,9,...,663,664,665,666,667,668,669,670,671,672
p_id,,,,,,,,,,,,,,,,,,,,,
0,1.000000,0.579112,0.367929,0.305464,0.611866,0.450289,0.645381,0.252068,0.423447,0.413212,...,0.412265,0.246988,0.320656,0.142549,0.0,0.300396,0.339220,0.553484,0.200126,0.373534
1,0.579112,1.000000,0.623414,0.569200,0.481713,0.484193,0.634612,0.221880,0.589657,0.610118,...,0.573846,0.282020,0.345991,0.162313,0.0,0.279554,0.424574,0.289549,0.246667,0.133159
2,0.367929,0.623414,1.000000,0.813538,0.334698,0.330447,0.681309,0.223733,0.802766,0.852585,...,0.525937,0.237191,0.495097,0.195985,0.0,0.207903,0.517087,0.163644,0.143246,0.051644
3,0.305464,0.569200,0.813538,1.000000,0.252219,0.248864,0.472246,0.168677,0.693568,0.779814,...,0.401869,0.187691,0.376546,0.069978,0.0,0.147237,0.369377,0.119406,0.081248,0.068107
4,0.611866,0.481713,0.334698,0.252219,1.000000,0.505322,0.469331,0.200703,0.357556,0.341513,...,0.440531,0.325029,0.348963,0.162615,0.0,0.213731,0.333713,0.083854,0.173714,0.356913

In [142]:
eat_review =pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data/광진구_cafe_review.csv')
eat_review

,res_name,user_name,review,rating,p_id,u_id
0,스타벅스,양양,"먹은 거: 오늘의커피(3,800원) 조각케익친절함.매장 청결함.공부하는 사람과 대화...",3,63,416
1,카페샛길,달리자크롱,"건대에서 조용히 얘기하면서 좋은 시간 보낼 수 있는 카페, 샛길자주 가도 리뷰 한번...",5,110,252
2,투썸플레이스,muk_so.o,여러번 먹고 쓰는 리뷰 43스트로베리 요거 프라페/ 딸기 프라페에 요거트가 들어가고...,3,132,148
3,투썸플레이스,뒤빈,시간이 잠깐 떠서 + 이대 근처에 투썸이 없었는데 생겼길래 가봤어요. 신규 매장이라...,3,132,266
4,카페구들,심아호,아주 만족스러웠습니다!가게는 작은데 사장님두 넘넘 친절하시고 분위기도 따숩고 좋았어...,5,103,406
...,...,...,...,...,...,...
1194,스타벅스,뽐뭉,층이 여러개인 매장이지만 매장내부에서 층간 연결이 되어있지않아 주문후 다른층으로 이...,0,63,367
1195,탭플레이,수연,생딸기 모히또 맛있네여! 애플민트를 직접 빻아서 만든다고 되어있어요. 모히또 전문점...,5,129,390
1196,투썸플레이스,먹방꼬북,쾌적하고 좋아요,3,132,317
1197,카페모든날,슈빙,친구 강아지 데려갈 수 있는 카페 찾아서 갔던 곳.시그니처 아인슈페너 마셨는데 많이...,3,109,394
1198,카페모든날,뇽뇽,애견카페는 많은데 애견동반카페는 근처에 없어서 폭풍검색 끝에 찾게된 카페 모든 날....,3,109,242

In [143]:
eat_review['u_id'].value_counts()

421    61
394    27
252    22
78     19
551    19
       ..
260     1
156     1
426     1
64      1
367     1
Name: u_id, Length: 600, dtype: int64

In [144]:
eat_review['rating'].value_counts()

5    753
3    361
0     85
Name: rating, dtype: int64

In [145]:
len(eat_review['p_id'].unique())

151

In [146]:
eat_review.drop(['review','res_name','user_name'],axis=1, inplace=True)

In [147]:
eat_review

      rating  p_id  u_id
0          3    63   416
1          5   110   252
2          3   132   148
3          3   132   266
4          5   103   406
...      ...   ...   ...
1194       0    63   367
1195       5   129   390
1196       3   132   317
1197       3   109   394
1198       3   109   242

[1199 rows x 3 columns]

In [148]:
eat_review_mean=eat_review.groupby(['u_id','p_id']).mean()
eat_review_mean

           rating
u_id p_id
0    15      3.00
1    57      2.75
     63      3.00
2    119     3.00
3    149     5.00
...           ...
598  7       5.00
     99      5.00
     120     3.00
599  66      5.00
     106     5.00

[1076 rows x 1 columns]

In [149]:
eat_review_mean.reset_index(level=0, inplace=True)
eat_review_mean.reset_index(level=0, inplace=True)
eat_review_mean

      p_id  u_id  rating
0       15     0    3.00
1       57     1    2.75
2       63     1    3.00
3      119     2    3.00
4      149     3    5.00
...    ...   ...     ...
1071     7   598    5.00
1072    99   598    5.00
1073   120   598    3.00
1074    66   599    5.00
1075   106   599    5.00

[1076 rows x 3 columns]

In [150]:
eat_review_mean.shape

(1076, 3)

In [151]:
# eat_review_mean_dropDU=eat_review_mean.drop_duplicates(subset=['u_id','p_id'], keep='first', ignore_index=False)

In [152]:
# eat_review_mean_dropDU.shape

In [153]:
import tensorflow as tf

In [154]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

train_df, test_df = train_test_split(eat_review_mean, test_size=0.2, random_state=123)

In [155]:
train_df.shape

(860, 3)

In [156]:
test_userids =list(set(test_df['u_id'].values))
len(test_userids)

168

In [157]:
all_userids =list(set(eat_review_mean['u_id'].values))
len(all_userids)#############################

600

In [158]:
user_record_df=eat_review[eat_review['u_id']==1567]

In [159]:
user_record_df

Empty DataFrame
Columns: [rating, p_id, u_id]
Index: []

In [160]:
user_record_df['p_id']

Series([], Name: p_id, dtype: int64)

In [161]:
#user record df

In [162]:
user_sim_df= cs_p_df.loc[user_record_df['p_id']]
user_sim_df

Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]
Index: []

[0 rows x 673 columns]

In [163]:
 user_record_df=train_df.loc[train_df['u_id']==int(1567),:]
 user_record_df

Empty DataFrame
Columns: [p_id, u_id, rating]
Index: []

In [164]:
user_sim_df= cs_u_df.loc[user_record_df['p_id']]
user_sim_df

Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]
Index: []

[0 rows x 600 columns]

In [165]:
user_rating_df = user_record_df[['rating']] 
user_rating_df

Empty DataFrame
Columns: [rating]
Index: []

In [166]:
#prediction

In [167]:
 prediction =np.matmul(user_sim_df.T.to_numpy() , user_rating_df.to_numpy()).flatten()
 prediction

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.])

In [168]:
result_df =pd.DataFrame()

for user_id in tqdm(all_userids):
  user_record_df = eat_review_mean.loc[eat_review_mean['u_id']==int(user_id),:] # (n,3) 

  user_sim_df= cs_p_df.loc[user_record_df['p_id']] #(n,1730). #1730개......##A
  user_rating_df = user_record_df[['rating']] #(n,1)##B
  sim_sum = np.sum(user_sim_df.T.to_numpy(),-1)


  prediction =np.matmul(user_sim_df.T.to_numpy() , user_rating_df.to_numpy()).flatten() /(sim_sum+1)##AB
  
  prediction_df = pd.DataFrame(prediction , index = cs_p_df.index).reset_index()
  prediction_df.columns=['p_id', 'pred_rating']
  prediction_df = prediction_df[['p_id', 'pred_rating']][prediction_df['p_id'].isin(test_df[test_df['u_id'] == user_id]['p_id'].values)]

  temp_df = prediction_df.merge(test_df[test_df['u_id'] == user_id], on='p_id')
  result_df = pd.concat([result_df, temp_df], axis=0)

100%|██████████| 600/600 [00:05<00:00, 111.20it/s]

In [171]:
result_df.head(10)

   pred_rating  p_id  u_id  rating
0     2.500000     2     6     5.0
0     2.500000    63    10     5.0
0     2.841332    21    21     5.0
0     1.500000    63    26     3.0
0     2.558707   122    27     5.0
0     2.500000    63    29     5.0
0     0.463696    19    34     0.0
0     2.500000    66    35     5.0
0     3.076108    66    40     5.0
0     2.893128    19    44     5.0

In [172]:
result_df.shape

(216, 4)

In [173]:
result_df['pred_rating'].mean()

2.4014064080677002

In [174]:
result_df['rating'].mean()

4.044753086419753

In [175]:

mse = mean_squared_error(y_true=result_df['rating'].values, y_pred=result_df['pred_rating'].values)
rmse = np.sqrt(mse)

print(mse, rmse)

3.8406176676110726 1.9597493889809157