In [1]:
import pandas as pd
import numpy as np
import math

In [2]:
# get size of vector
def mag(x):
    return math.sqrt(sum(i**2 for i in x))

In [5]:
res_matrix = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data/광진구_restuarant_res_matrix.csv')
user_matrix = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data/광진구_restuarant_user_matrix.csv')
group_count = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data/광진구_restuarant_group_count.csv',names=['group','count'])

In [6]:
res_matrix

,Unnamed: 0,group_64,group_0,group_1,group_2,group_3,group_4,group_5,group_6,group_7,...,group_110,group_111,group_112,group_113,group_114,group_115,group_116,group_117,group_118,group_119
0,0,274,19,14,1,8,4,6,16,9,...,0,0,41,28,31,7,0,4,4,15
1,1,77,6,11,2,5,9,4,8,6,...,0,0,53,14,22,9,0,8,2,5
2,2,26,7,2,1,2,1,0,1,6,...,0,0,7,13,3,5,0,0,0,1
3,3,23,2,1,1,0,2,1,15,3,...,0,0,5,6,3,5,0,0,6,2
4,4,4,0,0,0,0,0,0,0,0,...,0,0,0,5,0,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
668,668,1,0,0,0,0,0,0,0,0,...,0,0,3,0,0,0,0,0,0,0
669,669,9,0,2,0,0,0,1,0,2,...,0,0,7,6,1,3,0,0,0,1
670,670,13,0,1,0,1,1,0,1,0,...,0,0,1,2,1,0,0,0,1,0
671,671,5,0,0,1,0,0,0,0,0,...,0,0,0,3,2,0,0,0,1,0
672,672,3,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [7]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [8]:
group_count.drop([0], inplace =True)

In [9]:
res_matrix.rename(columns={'Unnamed: 0':'p_id'}, inplace=True)
res_matrix.set_index('p_id', drop=True, inplace=True)
group_count.set_index('group', drop=True, inplace=True)

In [10]:
user_matrix

,Unnamed: 0,group_64,group_0,group_1,group_2,group_3,group_4,group_5,group_6,group_7,...,group_110,group_111,group_112,group_113,group_114,group_115,group_116,group_117,group_118,group_119
0,876,12,2,0,0,1,4,0,10,1,...,0,0,6,2,1,2,0,0,0,0
1,1049,1,0,0,0,0,0,0,0,0,...,0,0,2,0,0,0,0,0,0,0
2,674,7,0,0,0,1,0,1,2,0,...,0,0,2,3,0,2,0,0,0,0
3,1596,7,1,1,0,0,0,0,5,0,...,0,0,2,1,1,1,0,1,0,0
4,2150,3,0,0,0,0,0,0,1,0,...,0,0,1,1,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2527,434,0,2,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
2528,2485,2,0,0,0,0,2,0,2,0,...,0,0,1,0,0,0,0,0,0,0
2529,1621,1,0,0,0,1,0,0,0,0,...,0,0,0,2,0,0,0,0,0,1
2530,333,2,0,1,0,0,2,1,5,0,...,0,0,2,0,0,0,0,0,0,0
2531,137,1,0,0,0,0,1,0,1,0,...,0,0,1,0,0,1,0,0,0,0

In [11]:
user_matrix.rename(columns={'Unnamed: 0':'u_id'}, inplace=True)
# user_matrix.set_index('u_id', drop=True, inplace=True)

In [12]:
user_matrix

,u_id,group_64,group_0,group_1,group_2,group_3,group_4,group_5,group_6,group_7,...,group_110,group_111,group_112,group_113,group_114,group_115,group_116,group_117,group_118,group_119
0,876,12,2,0,0,1,4,0,10,1,...,0,0,6,2,1,2,0,0,0,0
1,1049,1,0,0,0,0,0,0,0,0,...,0,0,2,0,0,0,0,0,0,0
2,674,7,0,0,0,1,0,1,2,0,...,0,0,2,3,0,2,0,0,0,0
3,1596,7,1,1,0,0,0,0,5,0,...,0,0,2,1,1,1,0,1,0,0
4,2150,3,0,0,0,0,0,0,1,0,...,0,0,1,1,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2527,434,0,2,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
2528,2485,2,0,0,0,0,2,0,2,0,...,0,0,1,0,0,0,0,0,0,0
2529,1621,1,0,0,0,1,0,0,0,0,...,0,0,0,2,0,0,0,0,0,1
2530,333,2,0,1,0,0,2,1,5,0,...,0,0,2,0,0,0,0,0,0,0
2531,137,1,0,0,0,0,1,0,1,0,...,0,0,1,0,0,1,0,0,0,0

In [13]:
user_matrix.set_index('u_id', drop=True, inplace=True)

In [14]:
user_matrix

,group_64,group_0,group_1,group_2,group_3,group_4,group_5,group_6,group_7,group_8,...,group_110,group_111,group_112,group_113,group_114,group_115,group_116,group_117,group_118,group_119
u_id,,,,,,,,,,,,,,,,,,,,,
876,12,2,0,0,1,4,0,10,1,0,...,0,0,6,2,1,2,0,0,0,0
1049,1,0,0,0,0,0,0,0,0,0,...,0,0,2,0,0,0,0,0,0,0
674,7,0,0,0,1,0,1,2,0,0,...,0,0,2,3,0,2,0,0,0,0
1596,7,1,1,0,0,0,0,5,0,0,...,0,0,2,1,1,1,0,1,0,0
2150,3,0,0,0,0,0,0,1,0,0,...,0,0,1,1,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
434,0,2,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
2485,2,0,0,0,0,2,0,2,0,0,...,0,0,1,0,0,0,0,0,0,0
1621,1,0,0,0,1,0,0,0,0,0,...,0,0,0,2,0,0,0,0,0,1
333,2,0,1,0,0,2,1,5,0,0,...,0,0,2,0,0,0,0,0,0,0
137,1,0,0,0,0,1,0,1,0,0,...,0,0,1,0,0,1,0,0,0,0

In [15]:
res_matrix

,group_64,group_0,group_1,group_2,group_3,group_4,group_5,group_6,group_7,group_8,...,group_110,group_111,group_112,group_113,group_114,group_115,group_116,group_117,group_118,group_119
p_id,,,,,,,,,,,,,,,,,,,,,
0,274,19,14,1,8,4,6,16,9,0,...,0,0,41,28,31,7,0,4,4,15
1,77,6,11,2,5,9,4,8,6,0,...,0,0,53,14,22,9,0,8,2,5
2,26,7,2,1,2,1,0,1,6,0,...,0,0,7,13,3,5,0,0,0,1
3,23,2,1,1,0,2,1,15,3,0,...,0,0,5,6,3,5,0,0,6,2
4,4,0,0,0,0,0,0,0,0,0,...,0,0,0,5,0,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
668,1,0,0,0,0,0,0,0,0,0,...,0,0,3,0,0,0,0,0,0,0
669,9,0,2,0,0,0,1,0,2,0,...,0,0,7,6,1,3,0,0,0,1
670,13,0,1,0,1,1,0,1,0,0,...,0,0,1,2,1,0,0,0,1,0
671,5,0,0,1,0,0,0,0,0,0,...,0,0,0,3,2,0,0,0,1,0
672,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [16]:
group_count.head()

          count
group
group_64    786
group_0      45
group_1      80
group_2      13
group_3      32

In [17]:
p_m = pd.DataFrame(np.array(res_matrix) * (1/np.array(group_count['count'])), index=res_matrix.index)
p_m = p_m.iloc[:,:].div(p_m.sum(axis=1), axis=0).fillna(0)
u_m = pd.DataFrame(np.array(user_matrix) * (1/np.array(group_count['count'])), index=user_matrix.index)
u_m = u_m.iloc[:,:].div(u_m.sum(axis=1), axis=0).fillna(0)

In [18]:
p_m

,0,1,2,3,4,5,6,7,8,9,...,110,111,112,113,114,115,116,117,118,119
p_id,,,,,,,,,,,,,,,,,,,,,
0,0.009248,0.011201,0.004642,0.002041,0.006632,0.003216,0.009363,0.011790,0.003061,0.0,...,0.0,0.0,0.015319,0.003641,0.016125,0.005627,0.0,0.002258,0.003216,0.018949
1,0.002892,0.003935,0.004058,0.004541,0.004612,0.008050,0.006945,0.006559,0.002270,0.0,...,0.0,0.0,0.022033,0.002026,0.012732,0.008050,0.0,0.005024,0.001789,0.007028
2,0.004351,0.020462,0.003289,0.010119,0.008221,0.003986,0.000000,0.003654,0.010119,0.0,...,0.0,0.0,0.012969,0.008383,0.007738,0.019930,0.0,0.000000,0.000000,0.006264
3,0.002661,0.004042,0.001137,0.006995,0.000000,0.005511,0.005349,0.037890,0.003498,0.0,...,0.0,0.0,0.006404,0.002675,0.005349,0.013778,0.0,0.000000,0.016534,0.008660
4,0.004077,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.000000,0.019633,0.000000,0.024274,0.0,0.017044,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
668,0.005826,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.193496,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
669,0.003765,0.000000,0.008221,0.000000,0.000000,0.000000,0.019343,0.000000,0.008432,0.0,...,0.0,0.0,0.032420,0.009672,0.006448,0.029894,0.0,0.000000,0.000000,0.015659
670,0.005337,0.000000,0.004033,0.000000,0.010083,0.009777,0.000000,0.008963,0.000000,0.0,...,0.0,0.0,0.004544,0.003163,0.006327,0.000000,0.0,0.000000,0.009777,0.000000
671,0.006467,0.000000,0.000000,0.078205,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.000000,0.014951,0.039869,0.000000,0.0,0.000000,0.030808,0.000000
672,0.026739,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,...,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000

In [19]:
u_m

,0,1,2,3,4,5,6,7,8,9,...,110,111,112,113,114,115,116,117,118,119
u_id,,,,,,,,,,,,,,,,,,,,,
876,0.003000,0.008735,0.000000,0.0,0.006142,0.023822,0.000000,0.054591,0.00252,0.0,...,0.0,0.0,0.016608,0.001927,0.003853,0.011911,0.0,0.00000,0.0,0.000000
1049,0.004781,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.00000,0.0,...,0.0,0.0,0.105848,0.000000,0.000000,0.000000,0.0,0.00000,0.0,0.000000
674,0.003552,0.000000,0.000000,0.0,0.012465,0.000000,0.023463,0.022160,0.00000,0.0,...,0.0,0.0,0.011236,0.005866,0.000000,0.024174,0.0,0.00000,0.0,0.000000
1596,0.007806,0.019479,0.010957,0.0,0.000000,0.000000,0.000000,0.121741,0.00000,0.0,...,0.0,0.0,0.024691,0.004297,0.017187,0.026562,0.0,0.01865,0.0,0.000000
2150,0.007469,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.054358,0.00000,0.0,...,0.0,0.0,0.027562,0.009593,0.000000,0.059300,0.0,0.00000,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
434,0.000000,0.213317,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.00000,0.0,...,0.0,0.0,0.067600,0.000000,0.000000,0.000000,0.0,0.00000,0.0,0.000000
2485,0.005901,0.000000,0.000000,0.0,0.000000,0.140559,0.000000,0.128845,0.00000,0.0,...,0.0,0.0,0.032665,0.000000,0.000000,0.000000,0.0,0.00000,0.0,0.000000
1621,0.001016,0.000000,0.000000,0.0,0.024956,0.000000,0.000000,0.000000,0.00000,0.0,...,0.0,0.0,0.000000,0.007829,0.000000,0.000000,0.0,0.00000,0.0,0.038028
333,0.001466,0.000000,0.007200,0.0,0.000000,0.034909,0.033882,0.079999,0.00000,0.0,...,0.0,0.0,0.016225,0.000000,0.000000,0.000000,0.0,0.00000,0.0,0.000000
137,0.004655,0.000000,0.000000,0.0,0.000000,0.110879,0.000000,0.101639,0.00000,0.0,...,0.0,0.0,0.051535,0.000000,0.000000,0.110879,0.0,0.00000,0.0,0.000000

In [20]:
p_m.to_csv('/content/drive/MyDrive/Colab Notebooks/data/광진구_restuarant_normalized_item_matrix.csv')
u_m.to_csv('/content/drive/MyDrive/Colab Notebooks/data/광진구_restuarant_normalized_user_matrix.csv')

In [21]:
group_count.to_csv('/content/drive/MyDrive/Colab Notebooks/data/광진구_restuarant_group_count.csv')