In [1]:
import pandas as pd
import numpy as np
import math
from tqdm import tqdm

In [2]:
# get size of vector
def mag(x):
    return math.sqrt(sum(i**2 for i in x))

In [9]:
p_m = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data/광진구_restuarant_normalized_item_matrix.csv')
u_m = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data/광진구_restuarant_normalized_user_matrix.csv')
group_count = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data/광진구_restuarant_group_count.csv')

# res_matrix.rename(columns ={'Unnamed: 0':'p_id' }, inplace =True)
p_m.set_index('p_id', inplace =True)
# user_matrix.rename(columns ={'Unnamed: 0':'u_id' }, inplace =True)
u_m.set_index('u_id', inplace =True)
# group_count.rename(columns ={'Unnamed: 0':'group' }, inplace =True)
# group_count.set_index('group', inplace =True)
# res_matrix.set_index('p_id', drop=True, inplace=True)
# user_matrix.set_index('u_id', drop=True, inplace=True)
# group_count.set_index('group', drop=True, inplace=True)

In [8]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [10]:
group_count

         group  count
0     group_50   1143
1      group_0    302
2      group_1     19
3      group_2    148
4      group_3     88
..         ...    ...
115  group_115      1
116  group_116     20
117  group_117    201
118  group_118    164
119  group_119     59

[120 rows x 2 columns]

In [11]:
group_count.set_index('group', inplace =True)

In [12]:
group_count

           count
group
group_50    1143
group_0      302
group_1       19
group_2      148
group_3       88
...          ...
group_115      1
group_116     20
group_117    201
group_118    164
group_119     59

[120 rows x 1 columns]

In [13]:
p_m

,0,1,2,3,4,5,6,7,8,9,...,110,111,112,113,114,115,116,117,118,119
p_id,,,,,,,,,,,,,,,,,,,,,
0,0.002643,0.004286,0.000000,0.000000,0.014710,0.000000,0.020226,0.000000,0.0,0.000000,...,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.008587,0.010524,0.007314
1,0.003184,0.004382,0.000000,0.002235,0.015038,0.006127,0.041356,0.000000,0.0,0.000000,...,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.033084,0.004938,0.004035,0.016823
2,0.003981,0.002152,0.000000,0.003953,0.011819,0.003611,0.055862,0.003862,0.0,0.000000,...,0.0,0.000000,0.000000,0.0,0.014553,0.0,0.039002,0.006145,0.007531,0.004407
3,0.003281,0.002922,0.000000,0.010434,0.003760,0.002043,0.029300,0.005461,0.0,0.002690,...,0.0,0.004243,0.009348,0.0,0.009878,0.0,0.011031,0.003293,0.001345,0.003739
4,0.003967,0.002071,0.000000,0.007396,0.017769,0.002896,0.017103,0.003483,0.0,0.015255,...,0.0,0.000000,0.000000,0.0,0.004668,0.0,0.015637,0.007779,0.000953,0.010601
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
768,0.000568,0.000000,0.068344,0.013161,0.007378,0.000000,0.020290,0.001607,0.0,0.000000,...,0.0,0.000000,0.000000,0.0,0.009691,0.0,0.000000,0.000000,0.000000,0.000000
769,0.003909,0.000000,0.000000,0.000000,0.016924,0.027579,0.000000,0.000000,0.0,0.072647,...,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000
770,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,...,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.116407,0.161787
771,0.007994,0.000000,0.000000,0.000000,0.103835,0.000000,0.000000,0.000000,0.0,0.000000,...,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.055716,0.154873
772,0.011310,0.042807,0.000000,0.000000,0.000000,0.000000,0.000000,0.031999,0.0,0.000000,...,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.157655,0.000000

In [14]:
u_m

,0,1,2,3,4,5,6,7,8,9,...,110,111,112,113,114,115,116,117,118,119
u_id,,,,,,,,,,,,,,,,,,,,,
559,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.00000,0.000000,0.000000
3735,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.00000,0.000000,0.000000
1961,0.002156,0.008162,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.00000,0.000000,0.041777
4100,0.004476,0.000000,0.0,0.000000,0.058132,0.0,0.000000,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.00000,0.000000,0.000000
3990,0.006306,0.006509,0.0,0.004427,0.007446,0.0,0.020476,0.008109,0.0,0.0,...,0.0,0.0,0.0,0.0,0.009779,0.0,0.098284,0.00652,0.023972,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1899,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.00000,0.000000,0.000000
3576,0.019914,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.00000,0.000000,0.000000
494,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.112915,0.0,0.000000,0.00000,0.000000,0.000000
2949,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.00000,0.000000,0.000000
758,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.00000,0.000000,0.000000

In [15]:
from sklearn.metrics.pairwise import cosine_similarity

def cos_sim_matrix(a,b):
  cos_sim=cosine_similarity(a,b)
  result_df =pd.DataFrame(data=cos_sim, index=[a.index])

  return result_df

In [16]:
#similarity df

In [17]:

cs_u_df = cos_sim_matrix(u_m,u_m)
cs_u_df.head()

,0,1,2,3,4,5,6,7,8,9,...,4171,4172,4173,4174,4175,4176,4177,4178,4179,4180
u_id,,,,,,,,,,,,,,,,,,,,,
559,1.000000,0.0,0.091133,0.488476,0.323648,0.000000,0.089901,0.345166,0.020197,0.067254,...,0.042793,0.222360,0.053531,0.000000,0.138421,0.020478,0.144098,0.112005,0.0,0.0
3735,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
1961,0.091133,0.0,1.000000,0.150550,0.372407,0.049328,0.553769,0.365550,0.030232,0.058675,...,0.040832,0.206745,0.049772,0.000000,0.401134,0.014280,0.134153,0.161774,0.0,0.0
4100,0.488476,0.0,0.150550,1.000000,0.426718,0.000000,0.267948,0.726704,0.048349,0.155948,...,0.127545,0.662741,0.159549,0.158864,0.439966,0.006104,0.429817,0.333829,0.0,0.0
3990,0.323648,0.0,0.372407,0.426718,1.000000,0.155775,0.434200,0.532239,0.065533,0.433540,...,0.212661,0.376423,0.091225,0.068309,0.438639,0.012278,0.244810,0.216255,0.0,0.0

In [18]:
cs_p_df = cos_sim_matrix(p_m,p_m)
cs_p_df.head()

,0,1,2,3,4,5,6,7,8,9,...,763,764,765,766,767,768,769,770,771,772
p_id,,,,,,,,,,,,,,,,,,,,,
0,1.000000,0.647579,0.623180,0.424532,0.486875,0.214828,0.546659,0.670088,0.309702,0.234277,...,0.616352,0.572123,0.619846,0.596737,0.250102,0.330721,0.129932,0.302030,0.417509,0.255292
1,0.647579,1.000000,0.848960,0.449983,0.521386,0.309457,0.750707,0.673894,0.453841,0.430299,...,0.832082,0.640462,0.643494,0.822681,0.279045,0.451438,0.126417,0.423521,0.541371,0.387781
2,0.623180,0.848960,1.000000,0.534479,0.587202,0.351009,0.688723,0.711630,0.507944,0.305681,...,0.762894,0.638065,0.688590,0.779959,0.271648,0.416789,0.207464,0.399065,0.466340,0.311748
3,0.424532,0.449983,0.534479,1.000000,0.447110,0.337392,0.411004,0.477290,0.255891,0.333623,...,0.394108,0.363092,0.490488,0.389121,0.158162,0.205859,0.122394,0.165719,0.231582,0.197811
4,0.486875,0.521386,0.587202,0.447110,1.000000,0.395524,0.453980,0.580357,0.428454,0.233928,...,0.444247,0.400208,0.567865,0.415364,0.234573,0.283038,0.278192,0.195768,0.390826,0.308511

In [19]:
eat_review =pd.read_csv('/content/drive/MyDrive/Colab Notebooks/data/광진구_restaurant_review.csv')
eat_review

,res_name,user_name,review,rating,p_id,u_id
0,모터시티,Mike Kim,Love motor city pizza,5,243,559
1,김북순큰남비집,철준,맛있음,5,88,3735
2,김북순큰남비집,돼후니,"#돼훈맛집 #솔직돼훈맛있고, 든든하게 한식을 먹을 수 있는 곳! -맛 : 3.7점 ...",5,88,1961
3,김북순큰남비집,호리,[신사/김북순 큰남비집] 5/5오 좋다! 소리가 절로 나온 찌개 맛집이오~개인적으로...,5,88,4100
4,김북순큰남비집,하몽이,누구나 아는 맛 그러나 모두가 즐기는 맛 근처에서 뜨끈한 국물에 흰 쌀밥 생각나면 ...,5,88,3990
...,...,...,...,...,...,...
17130,깐부치킨,Crisp.,깐부 처음가서 그런데 구운마늘치킨 먹음.. 맛은 있대 좀 많이 기름진거 같았어요.,3,95,160
17131,깐부치킨,Miriam Park,We ordered the garlic soy chicken. The chicken...,3,95,570
17132,모터시티,호두꽈자,포치즈홀스맨 24900그릴드 치킨 아보카도 샐러드 16900 (발사믹)[공간]생긴 ...,3,243,4095
17133,모터시티,이영훈,디트로이트 스타일 피자 처음먹어보는데 맛있어요 ㅋㅋ 가격은 좀 나가지만 토마토 소스...,5,243,3341
17134,모터시티,Tbone213@u!,Tasted aaamazing as usual and spot on tangy sa...,3,243,758

In [20]:
eat_review['u_id'].value_counts()

812     127
3066    125
2582    123
3520    122
4        94
       ...
3907      1
2674      1
1860      1
3724      1
758       1
Name: u_id, Length: 4181, dtype: int64

In [21]:
eat_review['rating'].value_counts()

5    10576
3     4886
0     1673
Name: rating, dtype: int64

In [22]:
len(eat_review['p_id'].unique())

771

In [23]:
eat_review.drop(['review','res_name','user_name'],axis=1, inplace=True)

In [24]:
eat_review

       rating  p_id  u_id
0           5   243   559
1           5    88  3735
2           5    88  1961
3           5    88  4100
4           5    88  3990
...       ...   ...   ...
17130       3    95   160
17131       3    95   570
17132       3   243  4095
17133       5   243  3341
17134       3   243   758

[17135 rows x 3 columns]

In [25]:
eat_review_mean=eat_review.groupby(['u_id','p_id']).mean()
eat_review_mean

           rating
u_id p_id
0    82       3.0
     114      5.0
     243      3.0
     264      5.0
     306      3.0
...           ...
4180 264      5.0
     382      5.0
     491      3.0
     619      5.0
     659      3.0

[16002 rows x 1 columns]

In [26]:
eat_review_mean.reset_index(level=0, inplace=True)
eat_review_mean.reset_index(level=0, inplace=True)
eat_review_mean

       p_id  u_id  rating
0        82     0     3.0
1       114     0     5.0
2       243     0     3.0
3       264     0     5.0
4       306     0     3.0
...     ...   ...     ...
15997   264  4180     5.0
15998   382  4180     5.0
15999   491  4180     3.0
16000   619  4180     5.0
16001   659  4180     3.0

[16002 rows x 3 columns]

In [27]:
eat_review_mean.shape

(16002, 3)

In [28]:
# eat_review_mean_dropDU=eat_review_mean.drop_duplicates(subset=['u_id','p_id'], keep='first', ignore_index=False)

In [29]:
# eat_review_mean_dropDU.shape

In [30]:
import tensorflow as tf

In [31]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

train_df, test_df = train_test_split(eat_review_mean, test_size=0.2, random_state=123)

In [32]:
train_df.shape

(12801, 3)

In [33]:
test_userids =list(set(test_df['u_id'].values))
len(test_userids)

1654

In [34]:
all_userids =list(set(eat_review_mean['u_id'].values))
len(all_userids)

4181

In [35]:
user_record_df=eat_review[eat_review['u_id']==1567]

In [36]:
user_record_df

      rating  p_id  u_id
725        3   213  1567
4008       0   309  1567
4755       5   659  1567

In [37]:
user_record_df['p_id']

725     213
4008    309
4755    659
Name: p_id, dtype: int64

In [38]:
cs_u_df.loc[user_record_df['p_id']]

,0,1,2,3,4,5,6,7,8,9,...,4171,4172,4173,4174,4175,4176,4177,4178,4179,4180
u_id,,,,,,,,,,,,,,,,,,,,,
213,0.130572,0.0,0.229398,0.401073,0.458265,0.072271,0.328864,0.551211,0.441682,0.241162,...,0.117816,0.529423,0.138083,0.062101,0.445450,0.055762,0.343567,0.312131,0.0,0.0
309,0.158845,0.0,0.068653,0.187766,0.481536,0.100709,0.086675,0.270808,0.033133,0.055021,...,0.041258,0.214381,0.311214,0.077807,0.182592,0.000000,0.139108,0.107986,0.0,0.0
659,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0

In [39]:
#user record df

In [40]:
user_sim_df= cs_p_df.loc[user_record_df['p_id']]
user_sim_df

,0,1,2,3,4,5,6,7,8,9,...,763,764,765,766,767,768,769,770,771,772
p_id,,,,,,,,,,,,,,,,,,,,,
213,0.446897,0.510048,0.632714,0.386450,0.419736,0.206865,0.448759,0.463606,0.303083,0.164008,...,0.460729,0.379010,0.447367,0.505345,0.164406,0.260124,0.119755,0.248625,0.287206,0.222285
309,0.068938,0.073461,0.132618,0.069531,0.174982,0.012930,0.037219,0.131398,0.075442,0.000404,...,0.052442,0.053628,0.139424,0.216378,0.096275,0.016151,0.196703,0.000000,0.153838,0.001315
659,0.630210,0.742998,0.789850,0.520357,0.540876,0.360875,0.668498,0.591051,0.436619,0.251255,...,0.702619,0.679736,0.745271,0.745244,0.247873,0.370792,0.237017,0.371058,0.441764,0.372281

In [41]:
 user_record_df=train_df.loc[train_df['u_id']==int(1567),:]
 user_record_df

      p_id  u_id  rating
6037   213  1567     3.0
6039   659  1567     5.0
6038   309  1567     0.0

In [42]:
user_sim_df= cs_u_df.loc[user_record_df['p_id']]
user_sim_df

,0,1,2,3,4,5,6,7,8,9,...,4171,4172,4173,4174,4175,4176,4177,4178,4179,4180
u_id,,,,,,,,,,,,,,,,,,,,,
213,0.130572,0.0,0.229398,0.401073,0.458265,0.072271,0.328864,0.551211,0.441682,0.241162,...,0.117816,0.529423,0.138083,0.062101,0.445450,0.055762,0.343567,0.312131,0.0,0.0
659,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
309,0.158845,0.0,0.068653,0.187766,0.481536,0.100709,0.086675,0.270808,0.033133,0.055021,...,0.041258,0.214381,0.311214,0.077807,0.182592,0.000000,0.139108,0.107986,0.0,0.0

In [43]:
user_rating_df = user_record_df[['rating']] 
user_rating_df

      rating
6037     3.0
6039     5.0
6038     0.0

In [44]:
#prediction

In [45]:
 prediction =np.matmul(user_sim_df.T.to_numpy() , user_rating_df.to_numpy()).flatten()
 prediction

array([0.39171634, 0.        , 0.688195  , ..., 0.93639222, 0.        ,
       0.        ])

In [46]:
result_df =pd.DataFrame()

for user_id in tqdm(all_userids):
  user_record_df = eat_review_mean.loc[eat_review_mean['u_id']==int(user_id),:] # (n,3) 

  user_sim_df= cs_p_df.loc[user_record_df['p_id']] #(n,1730). #1730개......##A
  user_rating_df = user_record_df[['rating']] #(n,1)##B
  sim_sum = np.sum(user_sim_df.T.to_numpy(),-1)


  prediction =np.matmul(user_sim_df.T.to_numpy() , user_rating_df.to_numpy()).flatten() /(sim_sum+1)##AB
  
  prediction_df = pd.DataFrame(prediction , index = cs_p_df.index).reset_index()
  prediction_df.columns=['p_id', 'pred_rating']
  prediction_df = prediction_df[['p_id', 'pred_rating']][prediction_df['p_id'].isin(test_df[test_df['u_id'] == user_id]['p_id'].values)]

  temp_df = prediction_df.merge(test_df[test_df['u_id'] == user_id], on='p_id')
  result_df = pd.concat([result_df, temp_df], axis=0)

100%|██████████| 4181/4181 [00:35<00:00, 119.10it/s]

In [47]:
len(userids)

NameError: ignored

In [48]:
result_df.head(10)

   p_id  pred_rating  u_id  rating
0   435     2.701491     0     3.5
1   472     2.578864     0     3.0
2   551     2.622449     0     3.0
3   633     2.499430     0     0.0
4   713     2.657992     0     3.0
0   315     0.000000     1     3.0
1   598     1.500000     1     3.0
0    95     3.712659     4     3.0
1    98     3.764807     4     5.0
2   238     3.795485     4     5.0

In [49]:
result_df.shape

(3201, 4)

In [50]:
result_df['pred_rating'].mean()

2.804833321211203

In [51]:
result_df['rating'].mean()

3.878142247214412

In [52]:

mse = mean_squared_error(y_true=result_df['rating'].values, y_pred=result_df['pred_rating'].values)
rmse = np.sqrt(mse)

print(mse, rmse)

3.1297992182467445 1.7691238561069558